### ISSUE TITLE
cannot get a token

### ISSUE THREAD

**Issue by dnplkndll** [DropbaseHQ/dropbase#10]
follow the readme to create account
verify email
get a name prompt
https://app.dropbase.io/intro
307 with no apparent change to page. blocking DROPBASE_TOKEN for env

**Comment by stefaan1o** [comment]
I think I run against the same issue. When I try to 'create workspace' the following errors appear in the log.
![image](https://github.com/DropbaseHQ/dropbase/assets/33217113/11bcc381-cfb8-4c5e-b432-e589daf614d9)

**Comment by azhakhan** [comment]
tokens are no longer required
